import type { ClubePadrao, SelecaoPadrao, TorneioMeta, DadosTime } from './types';

// ===== CLUBES DEFAULT (EA FC 26) =====
export const CLUBES_DEFAULT: ClubePadrao[] = [
  // La Liga
  { id:'real-madrid',   nome:'Real Madrid',        forca:89, bandeira:'🇪🇸', liga:'La Liga',        logo:'👑' },
  { id:'barcelona',     nome:'Barcelona',           forca:87, bandeira:'🇪🇸', liga:'La Liga',        logo:'🔵🔴' },
  { id:'atletico-mad',  nome:'Atlético Madrid',     forca:84, bandeira:'🇪🇸', liga:'La Liga',        logo:'🔴⚪' },
  { id:'real-sociedad', nome:'Real Sociedad',       forca:80, bandeira:'🇪🇸', liga:'La Liga',        logo:'🔵⚪' },
  { id:'villarreal',    nome:'Villarreal',          forca:79, bandeira:'🇪🇸', liga:'La Liga',        logo:'🟡' },
  { id:'sevilla',       nome:'Sevilla',             forca:78, bandeira:'🇪🇸', liga:'La Liga',        logo:'🔴⚪' },
  // Premier League
  { id:'man-city',      nome:'Manchester City',     forca:88, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🩵' },
  { id:'liverpool',     nome:'Liverpool',           forca:87, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🔴' },
  { id:'arsenal',       nome:'Arsenal',             forca:86, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🔫' },
  { id:'chelsea',       nome:'Chelsea',             forca:83, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🦁' },
  { id:'man-utd',       nome:'Manchester United',   forca:82, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'👹' },
  { id:'tottenham',     nome:'Tottenham',           forca:81, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🐓' },
  { id:'newcastle',     nome:'Newcastle',           forca:81, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'⚫⚪' },
  { id:'aston-villa',   nome:'Aston Villa',         forca:82, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'🦁' },
  { id:'west-ham',      nome:'West Ham',            forca:79, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿', liga:'Premier League', logo:'⚒️' },
  // Bundesliga
  { id:'bayern',        nome:'Bayern Munich',       forca:87, bandeira:'🇩🇪', liga:'Bundesliga',     logo:'🔴⚪' },
  { id:'leverkusen',    nome:'Bayer Leverkusen',    forca:84, bandeira:'🇩🇪', liga:'Bundesliga',     logo:'⚫🔴' },
  { id:'dortmund',      nome:'Borussia Dortmund',   forca:83, bandeira:'🇩🇪', liga:'Bundesliga',     logo:'🟡⚫' },
  { id:'leipzig',       nome:'RB Leipzig',          forca:81, bandeira:'🇩🇪', liga:'Bundesliga',     logo:'🔵🔴' },
  // Serie A
  { id:'inter',         nome:'Inter Milan',         forca:85, bandeira:'🇮🇹', liga:'Serie A',        logo:'🔵⚫' },
  { id:'milan',         nome:'AC Milan',            forca:83, bandeira:'🇮🇹', liga:'Serie A',        logo:'🔴⚫' },
  { id:'napoli',        nome:'Napoli',              forca:82, bandeira:'🇮🇹', liga:'Serie A',        logo:'🔵' },
  { id:'juventus',      nome:'Juventus',            forca:82, bandeira:'🇮🇹', liga:'Serie A',        logo:'⚫⚪' },
  { id:'roma',          nome:'AS Roma',             forca:80, bandeira:'🇮🇹', liga:'Serie A',        logo:'🟡🔴' },
  { id:'lazio',         nome:'Lazio',               forca:79, bandeira:'🇮🇹', liga:'Serie A',        logo:'🦅' },
  // Ligue 1
  { id:'psg',           nome:'PSG',                 forca:86, bandeira:'🇫🇷', liga:'Ligue 1',        logo:'🗼' },
  { id:'monaco',        nome:'Monaco',              forca:80, bandeira:'🇫🇷', liga:'Ligue 1',        logo:'🎲' },
  // Portugal
  { id:'benfica',       nome:'Benfica',             forca:81, bandeira:'🇵🇹', liga:'Primeira Liga',  logo:'🦅' },
  { id:'porto',         nome:'Porto',               forca:80, bandeira:'🇵🇹', liga:'Primeira Liga',  logo:'🐉' },
  { id:'sporting',      nome:'Sporting CP',         forca:79, bandeira:'🇵🇹', liga:'Primeira Liga',  logo:'🦁' },
  // Holanda
  { id:'ajax',          nome:'Ajax',                forca:79, bandeira:'🇳🇱', liga:'Eredivisie',     logo:'🔴⚪' },
  { id:'feyenoord',     nome:'Feyenoord',           forca:78, bandeira:'🇳🇱', liga:'Eredivisie',     logo:'🔴⚫' },
  // Escócia
  { id:'celtic',        nome:'Celtic',              forca:78, bandeira:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', liga:'Scottish Prem',  logo:'🍀' },
  { id:'rangers',       nome:'Rangers',             forca:77, bandeira:'🏴󠁧󠁢󠁳󠁣󠁴󠁿', liga:'Scottish Prem',  logo:'🦁' },
  // Turquia
  { id:'galatasaray',   nome:'Galatasaray',         forca:79, bandeira:'🇹🇷', liga:'Süper Lig',      logo:'🔴🟡' },
];

// ===== SELEÇÕES DEFAULT =====
export const SELECOES_DEFAULT: SelecaoPadrao[] = [
  { id:'franca',     nome:'França',         forca:86, bandeira:'🇫🇷' },
  { id:'argentina',  nome:'Argentina',      forca:85, bandeira:'🇦🇷' },
  { id:'inglaterra', nome:'Inglaterra',     forca:84, bandeira:'🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id:'espanha',    nome:'Espanha',        forca:84, bandeira:'🇪🇸' },
  { id:'portugal',   nome:'Portugal',       forca:83, bandeira:'🇵🇹' },
  { id:'alemanha',   nome:'Alemanha',       forca:83, bandeira:'🇩🇪' },
  { id:'belgica',    nome:'Bélgica',        forca:82, bandeira:'🇧🇪' },
  { id:'holanda',    nome:'Holanda',        forca:82, bandeira:'🇳🇱' },
  { id:'italia',     nome:'Itália',         forca:81, bandeira:'🇮🇹' },
  { id:'croacia',    nome:'Croácia',        forca:80, bandeira:'🇭🇷' },
  { id:'uruguai',    nome:'Uruguai',        forca:80, bandeira:'🇺🇾' },
  { id:'colombia',   nome:'Colômbia',       forca:79, bandeira:'🇨🇴' },
  { id:'marrocos',   nome:'Marrocos',       forca:79, bandeira:'🇲🇦' },
  { id:'turquia',    nome:'Turquia',        forca:78, bandeira:'🇹🇷' },
  { id:'eua',        nome:'EUA',            forca:78, bandeira:'🇺🇸' },
  { id:'mexico',     nome:'México',         forca:78, bandeira:'🇲🇽' },
  { id:'austria',    nome:'Áustria',        forca:77, bandeira:'🇦🇹' },
  { id:'japao',      nome:'Japão',          forca:77, bandeira:'🇯🇵' },
  { id:'senegal',    nome:'Senegal',        forca:77, bandeira:'🇸🇳' },
  { id:'dinamarca',  nome:'Dinamarca',      forca:77, bandeira:'🇩🇰' },
  { id:'suica',      nome:'Suíça',          forca:76, bandeira:'🇨🇭' },
  { id:'chile',      nome:'Chile',          forca:75, bandeira:'🇨🇱' },
  { id:'polonia',    nome:'Polônia',        forca:75, bandeira:'🇵🇱' },
  { id:'australia',  nome:'Austrália',      forca:74, bandeira:'🇦🇺' },
  { id:'nigeria',    nome:'Nigéria',        forca:74, bandeira:'🇳🇬' },
  { id:'coreia',     nome:'Coreia do Sul',  forca:74, bandeira:'🇰🇷' },
  { id:'equador',    nome:'Equador',        forca:73, bandeira:'🇪🇨' },
  { id:'ghana',      nome:'Gana',           forca:72, bandeira:'🇬🇭' },
  { id:'peru',       nome:'Peru',           forca:72, bandeira:'🇵🇪' },
];

// ===== METADADOS DOS TORNEIOS =====
export const TORNEIO_META: Record<string, TorneioMeta> = {
  'champions':     { nome:'Champions League', tipo:'clubes', logo:'https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/UEFA_Champions_League.svg/512px-UEFA_Champions_League.svg.png' },
  'libertadores':  { nome:'Libertadores',     tipo:'clubes', logo:'https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Copa_Libertadores_logo.svg/512px-Copa_Libertadores_logo.svg.png' },
  'brasileirao':   { nome:'Brasileirão',      tipo:'clubes', logo:'https://upload.wikimedia.org/wikipedia/pt/thumb/8/89/Brasileir%C3%A3o_-_Log%C3%B3tipo.png/320px-Brasileir%C3%A3o_-_Log%C3%B3tipo.png' },
  'paulistao':     { nome:'Paulistão',        tipo:'clubes', logo:'https://upload.wikimedia.org/wikipedia/pt/thumb/6/66/Logo_Paulist%C3%A3o_2021.png/320px-Logo_Paulist%C3%A3o_2021.png' },
  'copa-brasil':   { nome:'Copa do Brasil',   tipo:'clubes', logo:'https://upload.wikimedia.org/wikipedia/pt/thumb/4/44/Copa_do_Brasil_logo.png/240px-Copa_do_Brasil_logo.png' },
  'copa-do-mundo': { nome:'Copa do Mundo',    tipo:'selecoes', logo:'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/2022_FIFA_World_Cup.svg/512px-2022_FIFA_World_Cup.svg.png' },
};

// ===== DADOS VISUAIS DOS TIMES =====
const FD = 'https://crests.football-data.org/';
export const TEAM_DATA: Record<string, DadosTime> = {
  'real-madrid':   { abrev:'RM',  fundo:'#FEFEFE', cor:'#00529F', pais:'es', paisNome:'Espanha',    crest:`${FD}86.png`  },
  'barcelona':     { abrev:'FCB', fundo:'#A50044', cor:'#FFD700', pais:'es', paisNome:'Espanha',    crest:`${FD}81.png`  },
  'atletico-mad':  { abrev:'ATM', fundo:'#CB3524', cor:'#FFFFFF', pais:'es', paisNome:'Espanha',    crest:`${FD}78.png`  },
  'real-sociedad': { abrev:'RSO', fundo:'#0066CC', cor:'#FFFFFF', pais:'es', paisNome:'Espanha',    crest:`${FD}92.png`  },
  'villarreal':    { abrev:'VIL', fundo:'#FFD700', cor:'#003366', pais:'es', paisNome:'Espanha',    crest:`${FD}94.png`  },
  'sevilla':       { abrev:'SEV', fundo:'#CC0000', cor:'#FFFFFF', pais:'es', paisNome:'Espanha',    crest:`${FD}559.png` },
  'man-city':      { abrev:'MCI', fundo:'#6CABDD', cor:'#FFFFFF', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}65.png`  },
  'liverpool':     { abrev:'LIV', fundo:'#C8102E', cor:'#FFD700', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}64.png`  },
  'arsenal':       { abrev:'ARS', fundo:'#EF0107', cor:'#FFFFFF', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}57.png`  },
  'chelsea':       { abrev:'CHE', fundo:'#034694', cor:'#FFFFFF', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}61.png`  },
  'man-utd':       { abrev:'MNU', fundo:'#DA291C', cor:'#FFD700', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}66.png`  },
  'tottenham':     { abrev:'TOT', fundo:'#132257', cor:'#FFFFFF', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}73.png`  },
  'newcastle':     { abrev:'NEW', fundo:'#241F20', cor:'#FFFFFF', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}67.png`  },
  'aston-villa':   { abrev:'AVL', fundo:'#670E36', cor:'#95BFE5', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}58.png`  },
  'west-ham':      { abrev:'WHU', fundo:'#7A263A', cor:'#1BB1E7', pais:'gb-eng', paisNome:'Inglaterra', crest:`${FD}563.png` },
  'bayern':        { abrev:'FCB', fundo:'#DC052D', cor:'#FFFFFF', pais:'de', paisNome:'Alemanha',   crest:`${FD}5.png`   },
  'leverkusen':    { abrev:'B04', fundo:'#E32221', cor:'#000000', pais:'de', paisNome:'Alemanha',   crest:`${FD}3.png`   },
  'dortmund':      { abrev:'BVB', fundo:'#FDE100', cor:'#000000', pais:'de', paisNome:'Alemanha',   crest:`${FD}4.png`   },
  'leipzig':       { abrev:'RBL', fundo:'#DD0741', cor:'#FFFFFF', pais:'de', paisNome:'Alemanha',   crest:`${FD}721.png` },
  'inter':         { abrev:'INT', fundo:'#003DA5', cor:'#000000', pais:'it', paisNome:'Itália',     crest:`${FD}108.png` },
  'milan':         { abrev:'ACM', fundo:'#FB090B', cor:'#000000', pais:'it', paisNome:'Itália',     crest:`${FD}98.png`  },
  'napoli':        { abrev:'NAP', fundo:'#12A0C3', cor:'#FFFFFF', pais:'it', paisNome:'Itália',     crest:`${FD}113.png` },
  'juventus':      { abrev:'JUV', fundo:'#000000', cor:'#FFFFFF', pais:'it', paisNome:'Itália',     crest:`${FD}109.png` },
  'roma':          { abrev:'ASR', fundo:'#8E1F2F', cor:'#FFD700', pais:'it', paisNome:'Itália',     crest:`${FD}100.png` },
  'lazio':         { abrev:'LAZ', fundo:'#87CEEB', cor:'#003366', pais:'it', paisNome:'Itália',     crest:`${FD}110.png` },
  'psg':           { abrev:'PSG', fundo:'#004170', cor:'#FFFFFF', pais:'fr', paisNome:'França',     crest:`${FD}524.png` },
  'monaco':        { abrev:'ASM', fundo:'#EE2523', cor:'#FFFFFF', pais:'fr', paisNome:'França',     crest:`${FD}548.png` },
  'benfica':       { abrev:'SLB', fundo:'#C8102E', cor:'#FFFFFF', pais:'pt', paisNome:'Portugal',  crest:`${FD}1903.png`},
  'porto':         { abrev:'FCP', fundo:'#003087', cor:'#FFD700', pais:'pt', paisNome:'Portugal',  crest:`${FD}503.png` },
  'sporting':      { abrev:'SCP', fundo:'#008136', cor:'#FFD700', pais:'pt', paisNome:'Portugal',  crest:`${FD}498.png` },
  'ajax':          { abrev:'AFC', fundo:'#C8102E', cor:'#FFFFFF', pais:'nl', paisNome:'Holanda',   crest:`${FD}610.png` },
  'feyenoord':     { abrev:'FEY', fundo:'#C8102E', cor:'#000000', pais:'nl', paisNome:'Holanda',   crest:`${FD}675.png` },
  'celtic':        { abrev:'CEL', fundo:'#00843D', cor:'#FFFFFF', pais:'gb-sct', paisNome:'Escócia', crest:`${FD}732.png` },
  'rangers':       { abrev:'RFC', fundo:'#003087', cor:'#FFFFFF', pais:'gb-sct', paisNome:'Escócia', crest:`${FD}733.png` },
  'galatasaray':   { abrev:'GS',  fundo:'#DD0000', cor:'#FFD700', pais:'tr', paisNome:'Turquia',   crest:`${FD}2320.png`},
};

// ===== MAPA PAÍS PARA SELEÇÃO =====
export const SELECAO_PAIS: Record<string, { pais: string; paisNome: string }> = {
  'franca':     { pais:'fr',    paisNome:'França'       },
  'argentina':  { pais:'ar',    paisNome:'Argentina'    },
  'inglaterra': { pais:'gb-eng', paisNome:'Inglaterra'  },
  'espanha':    { pais:'es',    paisNome:'Espanha'      },
  'portugal':   { pais:'pt',    paisNome:'Portugal'     },
  'alemanha':   { pais:'de',    paisNome:'Alemanha'     },
  'belgica':    { pais:'be',    paisNome:'Bélgica'      },
  'holanda':    { pais:'nl',    paisNome:'Holanda'      },
  'italia':     { pais:'it',    paisNome:'Itália'       },
  'croacia':    { pais:'hr',    paisNome:'Croácia'      },
  'uruguai':    { pais:'uy',    paisNome:'Uruguai'      },
  'colombia':   { pais:'co',    paisNome:'Colômbia'     },
  'marrocos':   { pais:'ma',    paisNome:'Marrocos'     },
  'turquia':    { pais:'tr',    paisNome:'Turquia'      },
  'eua':        { pais:'us',    paisNome:'EUA'          },
  'mexico':     { pais:'mx',    paisNome:'México'       },
  'austria':    { pais:'at',    paisNome:'Áustria'      },
  'japao':      { pais:'jp',    paisNome:'Japão'        },
  'senegal':    { pais:'sn',    paisNome:'Senegal'      },
  'dinamarca':  { pais:'dk',    paisNome:'Dinamarca'    },
  'suica':      { pais:'ch',    paisNome:'Suíça'        },
  'chile':      { pais:'cl',    paisNome:'Chile'        },
  'polonia':    { pais:'pl',    paisNome:'Polônia'      },
  'australia':  { pais:'au',    paisNome:'Austrália'    },
  'nigeria':    { pais:'ng',    paisNome:'Nigéria'      },
  'coreia':     { pais:'kr',    paisNome:'Coreia do Sul'},
  'equador':    { pais:'ec',    paisNome:'Equador'      },
  'ghana':      { pais:'gh',    paisNome:'Gana'         },
  'peru':       { pais:'pe',    paisNome:'Peru'         },
};
